// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: valuelog.proto

package value_log_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValueLogRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *uint64                `protobuf:"varint,4,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"` // optional
	Ttl           *uint64                `protobuf:"varint,5,opt,name=ttl,proto3,oneof" json:"ttl,omitempty"`             // time to live
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValueLogRecord) Reset() {
	*x = ValueLogRecord{}
	mi := &file_valuelog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueLogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueLogRecord) ProtoMessage() {}

func (x *ValueLogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_valuelog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueLogRecord.ProtoReflect.Descriptor instead.
func (*ValueLogRecord) Descriptor() ([]byte, []int) {
	return file_valuelog_proto_rawDescGZIP(), []int{0}
}

func (x *ValueLogRecord) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ValueLogRecord) GetTimestamp() uint64 {
	if x != nil && x.Timestamp != nil {
		return *x.Timestamp
	}
	return 0
}

func (x *ValueLogRecord) GetTtl() uint64 {
	if x != nil && x.Ttl != nil {
		return *x.Ttl
	}
	return 0
}

var File_valuelog_proto protoreflect.FileDescriptor

const file_valuelog_proto_rawDesc = "" +
	"\n" +
	"\x0evaluelog.proto\x12\tvalue_log\"v\n" +
	"\x0eValueLogRecord\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12!\n" +
	"\ttimestamp\x18\x04 \x01(\x04H\x00R\ttimestamp\x88\x01\x01\x12\x15\n" +
	"\x03ttl\x18\x05 \x01(\x04H\x01R\x03ttl\x88\x01\x01B\f\n" +
	"\n" +
	"_timestampB\x06\n" +
	"\x04_ttlB\x14Z\x12proto/value_log_pbb\x06proto3"

var (
	file_valuelog_proto_rawDescOnce sync.Once
	file_valuelog_proto_rawDescData []byte
)

func file_valuelog_proto_rawDescGZIP() []byte {
	file_valuelog_proto_rawDescOnce.Do(func() {
		file_valuelog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_valuelog_proto_rawDesc), len(file_valuelog_proto_rawDesc)))
	})
	return file_valuelog_proto_rawDescData
}

var file_valuelog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_valuelog_proto_goTypes = []any{
	(*ValueLogRecord)(nil), // 0: value_log.ValueLogRecord
}
var file_valuelog_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_valuelog_proto_init() }
func file_valuelog_proto_init() {
	if File_valuelog_proto != nil {
		return
	}
	file_valuelog_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_valuelog_proto_rawDesc), len(file_valuelog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_valuelog_proto_goTypes,
		DependencyIndexes: file_valuelog_proto_depIdxs,
		MessageInfos:      file_valuelog_proto_msgTypes,
	}.Build()
	File_valuelog_proto = out.File
	file_valuelog_proto_goTypes = nil
	file_valuelog_proto_depIdxs = nil
}
